name: Semantic Automatic Version Releaser

on:
  push:
    branches:
      - main

jobs:
  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required to get full git history

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.1

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Run Semantic Automatic Version Releaser
        uses: ./
        with:
          github-token: ${{ secrets.GH_TOKEN }}
